server:
  port: 8082

spring:
  application:
    name: quiz-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ai_dev_quiz}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
